### ISSUE TITLE
feature request: give sol distance in addition to equatorial coordinates

### ISSUE THREAD

**Issue by Artoria2e5** [EDSM-NET/Component#1]
the current equatorial coordinates does not quite uniquely identify a point in space. adding a sol distance could help. 

yes, it's as useful as equatorial coordinates, which is to say not at all in-game.

**Comment by klightspeed** [comment]
This should be given in the R value of the galactic coordinates (since both galactic and equatorial coordinates are heliocentric).

**Comment by Artoria2e5** [comment]
Indeed it is! And the ED coordinate system is also heliocentric...
